# Generated by Django 4.1.9 on 2023-06-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpdesk.tickets.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "ticket_type",
                    models.CharField(choices=[("I", "Incident"), ("R", "Request")], default="I", max_length=1),
                ),
                (
                    "ticket_number",
                    helpdesk.tickets.fields.TicketNumberField(
                        default=helpdesk.tickets.fields.TicketNumberField.generate_ticket_number,
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("C", "Critical"), ("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="L",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upvotes", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "New"), ("IP", "In Progress"), ("R", "Resolved"), ("C", "Closed")],
                        default="N",
                        max_length=2,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket")),
            ],
        ),
    ]
