# Generated by Django 4.1.9 on 2023-06-29 19:57

from django.db import migrations, models
import django.db.models.deletion
import helpdesk.tickets.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_remove_ticket_upvotes_alter_ticket_ticket_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketstatus",
            options={"get_latest_by": "created_at"},
        ),
        migrations.RenameField(
            model_name="ticketstatus",
            old_name="updated_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=helpdesk.tickets.fields.TicketNumberField(
                default=helpdesk.tickets.fields.TicketNumberField.generate_ticket_number, max_length=8, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticketstatus",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ticket_status", to="tickets.ticket"
            ),
        ),
    ]
