# Generated by Django 4.1.9 on 2023-07-11 16:19

from django.db import migrations, models
import helpdesk.tickets.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_alter_ticket_ticket_number_alter_ticketstatus_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=helpdesk.tickets.fields.TicketNumberField(
                default=helpdesk.tickets.fields.TicketNumberField.generate_ticket_number, max_length=8, unique=True
            ),
        ),
    ]
